### ISSUE TITLE
cannot import name 'fMPI' from 'quop_mpi.__lib'

### ISSUE THREAD

**Issue by ntyz** [Edric-Matwiejew/QuOp_MPI#4]
After I installed the QuOp_MPI according to the documentation, the following error occurred when importing the QuOp_MPI library in Python:

> ImportError: cannot import name 'fMPI' from 'quop_mpi.__lib' (../anaconda3/lib/python3.8/site-packages/quop_mpi/__lib/__init__.py)

I have clone the code and I entered the following command:

> python3 setup.py sdist bdist_wheel
> pip3 install quop_mpi-0.0.1.tar.gz
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<path to HDF5 lib>:<path to FFTW lib>
where <path to HDF5 lib>:<path to FFTW lib> is set according to setup.cfg

besides，I want to kown how do I confirm that there are FFTW and HDF5 library on the server and Where are the two libraries installed？

**Comment by Edric-Matwiejew** [comment]
Thanks for opening this issue.

I've pushed an update that simplifies the installation process (and corrects the bug you encountered). Please pull the most recent version of the default branch and re-attempt installation. 

The location of the HDF5 and FFTW libraries will depend on your host system. For most Unix-like systems they will be in /usr/lib and /usr/lib/include (or a sub-directory of these paths).

Let me know how the update works for you, I'll leave this open until then.
